googleapis/google-api-java-client

- README.md
Use the lattest version of the google-api-client library
> Use lattest version of library

- .travis.yml
@madongfly, please review. This look look familiar :)
> Disable Travis-CI email notifications

- google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/CloudShellCredentialTest.java
fix an earlier merge conflict in moe syncing process
> Fix 1234 merge

- README.md
> Generate instructions.html from README.md.

- google-api-client-appengine/pom.xml
- google-api-client/pom.xml
- pom.xml
> Bump version of Guava and Jackson Core.

- google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClient.java
fixes #1073 
@garrettjonesgoogle PTAL
> Default to "batch" if setBatchPath is never called.

- google-api-client/pom.xml
see #1034 
@elharo @garrettjonesgoogle PTAL
> Fixes #1018

- google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/DefaultCredentialProvider.java
> Check environment variables for appengine

- google-api-client/src/test/java/com/google/api/client/googleapis/media/MediaHttpUploaderTest.java
Linting errors fixed here and internally as part of two way sync.
> internal: fix linter errors

- README.md
- pom.xml
Also document steps to build and test, incl getting google-play-services jar installed.
> internal: readme cleanup

- google-api-client/src/main/java/com/google/api/client/googleapis/json/GoogleJsonResponseException.java
- google-api-client/src/test/java/com/google/api/client/googleapis/json/GoogleJsonResponseExceptionTest.java
See internal bug b/110777535 for additional context
Addresses #1117
> Fix key error

- google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleOAuthConstants.java
> Update token url

- .kokoro/build.sh
- .kokoro/common.cfg
- .kokoro/presubmit/common.cfg
- .kokoro/presubmit/java10.cfg
- .kokoro/presubmit/java7.cfg
- .kokoro/presubmit/java8.cfg
- .kokoro/presubmit/java9.cfg
- .kokoro/trampoline.sh
- google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java
- google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java
Also fixes the Java version reported in the header for Java 9. (which was inadvertently introduced in #1146)
> Add kokoro test configs

- pom.xml
> update appengine SDK

- pom.xml
> update minimum maven

- google-api-client-android/pom.xml
- google-api-client-appengine/pom.xml
- google-api-client-assembly/pom.xml
- google-api-client-gson/pom.xml
- google-api-client-jackson2/pom.xml
- google-api-client-java6/pom.xml
- google-api-client-protobuf/pom.xml
- google-api-client-servlet/pom.xml
- google-api-client-xml/pom.xml
- google-api-client/pom.xml
- pom.xml
- versions.txt
> Bump next snapshot

- google-api-client-bom/README.md
- google-api-client-bom/pom.xml
- pom.xml
> Add google-api-client-bom artifact

- google-api-client-assembly/dependencies/google-api-client-android-dependencies.html
- google-api-client-assembly/dependencies/google-api-client-appengine-dependencies.html
- google-api-client-assembly/dependencies/google-api-client-dependencies.html
- google-api-client-assembly/dependencies/google-api-client-gson-dependencies.html
- google-api-client-assembly/dependencies/google-api-client-jackson2-dependencies.html
- google-api-client-assembly/dependencies/google-api-client-java6-dependencies.html
- google-api-client-assembly/dependencies/google-api-client-protobuf-dependencies.html
- google-api-client-assembly/dependencies/google-api-client-servlet-dependencies.html
- google-api-client-assembly/dependencies/google-api-client-xml-dependencies.html
- google-api-client-assembly/dependencies/google-http-client-appengine-dependencies.html
- google-api-client-assembly/dependencies/google-http-client-dependencies.html
- google-api-client-assembly/dependencies/google-http-client-gson-dependencies.html
- google-api-client-assembly/dependencies/google-http-client-jackson-dependencies.html
- google-api-client-assembly/dependencies/google-http-client-jackson2-dependencies.html
- google-api-client-assembly/dependencies/google-http-client-jdo-dependencies.html
- google-api-client-assembly/dependencies/google-http-client-xml-dependencies.html
- google-api-client-assembly/dependencies/google-oauth-client-appengine-dependencies.html
- google-api-client-assembly/dependencies/google-oauth-client-dependencies.html
- google-api-client-assembly/dependencies/google-oauth-client-java6-dependencies.html
- google-api-client-assembly/dependencies/google-oauth-client-servlet-dependencies.html
- google-api-client-jackson2/pom.xml
- pom.xml
> Update guava to 26.0-android

- google-api-client/src/main/java/com/google/api/client/googleapis/testing/auth/oauth2/MockTokenServerTransport.java
> Set expires_in to an hour instead of 1000 hours

- pom.xml
> Use maven enforcer plugin for maven version requirements

- google-api-client-appengine/pom.xml
- google-api-client-gson/pom.xml
- google-api-client-jackson2/pom.xml
- google-api-client-java6/pom.xml
- google-api-client-protobuf/pom.xml
- google-api-client-servlet/pom.xml
- google-api-client-xml/pom.xml
- google-api-client/pom.xml
> Add automatic module name

- google-api-client-java6/pom.xml
> Bring comment in line with code

- google-api-client-appengine/pom.xml
- google-api-client-jackson2/pom.xml
- google-api-client-java6/pom.xml
- google-api-client-protobuf/pom.xml
- google-api-client-servlet/pom.xml
- google-api-client-xml/pom.xml
- google-api-client/pom.xml
@chingor13 Fixes #1018
- [X ] Tests pass
- [ X] Appropriate docs were updated (if necessary)
> More OSGI metadata

- README.md
- google-api-client-appengine/pom.xml
- google-api-client-gson/pom.xml
- google-api-client-jackson2/pom.xml
- google-api-client-java6/pom.xml
- google-api-client-protobuf/pom.xml
- google-api-client-servlet/pom.xml
- google-api-client-xml/pom.xml
- google-api-client/pom.xml
- pom.xml
> Fix doc links to googleapis.dev

- pom.xml
Use the bom rather than specifying multiple artifact versions which are
contained in the respective boms.
> Import google-http-client-bom and google-oauth-client-bom.

- google-api-client-assembly/pom.xml
removing non existing http client assembly dependency.
> remove non existing http client assembly pom dependency

- pom.xml
> remove unused variables and update Guava

- google-api-client-bom/pom.xml
> Specify versions for plugins in the bom pom.xml

- google-api-client-protobuf/pom.xml
- google-api-client/pom.xml
- pom.xml
> update protobuf to 3.9.1

- google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/OAuth2Utils.java
> Fix GKE Metadata Server Error

- google-api-client-assembly/android-properties/jackson-core-asl-1.9.11.jar.properties
- google-api-client-assembly/classpath-include
- google-api-client-assembly/dependencies/google-http-client-jackson-dependencies.html
- google-api-client-assembly/dependencies/google-oauth-client-dependencies.html
- google-api-client-assembly/dependencies/google-oauth-client-java6-dependencies.html
- google-api-client-assembly/readme.html
- pom.xml
We no longer depend on this.
@chingor13 
toward #1411
> remove jackson-core-asl

- pom.xml
> Update guava to 28.1-android

- google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java
> fix warnings

- google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java
- google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java
> fix: user-agent should use identifier/version

- docs/_config.yml
> Fix project name

- google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpUploader.java
> docs: fix link to media upload documentation

- google-api-client-protobuf/src/test/proto/simple_proto.proto
- google-api-client/src/test/proto/error_output.proto
- google-api-client/src/test/proto/mock_data.proto
fixes #1413 
Fixes some warnings in the build
@codyoss
> remove no longer supported option

- pom.xml
> update apache http client and GSON

- google-api-client/pom.xml
- google-api-client/src/main/java/com/google/api/client/googleapis/GoogleUtils.java
> keep GoogleUtils

- README.md
> docs: add google android repository to Gradle instructions

- pom.xml
> deps: update oauth client

- pom.xml
> fix: cleanup commented code of syncing versions in pom.xml

- google-api-client-appengine/pom.xml
- pom.xml
> deps: remove excess dependencies

- pom.xml
> deps: update to Guava 29.0

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
- .github/trusted-contribution.yml
- .github/workflows/ci.yaml
- .kokoro/build.bat
- .kokoro/build.sh
- .kokoro/common.sh
- .kokoro/continuous/java8.cfg
- .kokoro/dependencies.sh
- .kokoro/linkage-monitor.sh
- .kokoro/nightly/integration.cfg
- .kokoro/nightly/java8.cfg
- .kokoro/nightly/samples.cfg
- .kokoro/populate-secrets.sh
- .kokoro/presubmit/integration.cfg
- .kokoro/presubmit/java8.cfg
- .kokoro/presubmit/samples.cfg
- .kokoro/trampoline.sh
- .repo-metadata.json
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- samples/install-without-bom/pom.xml
- samples/pom.xml
- samples/snapshot/pom.xml
- samples/snippets/pom.xml
- synth.metadata
- synth.py
> chore: regenerate common templates

- .travis.yml
This has not been used for years
> chore: delete TravisCI config

- pom.xml
> deps: update Guava to 30.0

- docs/oauth-2.0.md
> chore(docs): Update code snippets to use newer version of GoogleCredentials

- .github/workflows/ci.yaml
- google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/GoogleIdTokenVerifierTest.java
- google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/GooglePublicKeysManagerTest.java
- google-api-client/src/test/java/com/google/api/client/googleapis/batch/BatchRequestTest.java
- synth.metadata
- synth.py
> ci: fix the google style error in lint task in GitHub Actions

- google-api-client-android/pom.xml
- google-api-client-appengine/pom.xml
- google-api-client-gson/pom.xml
- google-api-client-jackson2/pom.xml
- google-api-client-java6/pom.xml
- google-api-client-protobuf/pom.xml
- google-api-client-servlet/pom.xml
- google-api-client-xml/pom.xml
- google-api-client/pom.xml
- pom.xml
> ci: fix "ci / dependencies" GitHub checks

- pom.xml
@chingor13
renovatebot picked the wrong version
> deps: update guava

- google-api-client-protobuf/pom.xml
- google-api-client/pom.xml
- pom.xml
@Neenu1995 @chingor13 unbreak build
> build: update protobuf plugin

- .github/workflows/ci.yaml
- google-api-client-protobuf/pom.xml
- google-api-client/pom.xml
- pom.xml
> feat: configure initial sp version

- .github/workflows/ci.yaml
- .kokoro/build.sh
- .kokoro/presubmit/common.cfg
- codecov.yaml
- synth.metadata
> chore: remove codecov

- pom.xml
> deps: don't use sp versions in the regular release

- google-api-client-bom/pom.xml
> chore: migrate to sonatype endpoint

- pom.xml
If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).
> deps: downgrade appengine to 1.9.X

- .github/release-please.yml
- .github/sync-repo-settings.yaml
> feat: next release from main branch is 2.1.0

- .github/release-please.yml
- .github/sync-repo-settings.yaml
enable releases
```
release-brancher create-pull-request \
--branch-name="2.2.x" \
--target-tag="v2.2.0" \
--repo="googleapis/google-api-java-client" \
--pull-request-title="feat: setup 2.2.x lts branch" \
--release-type=java-backport
```
> feat: setup 2.2.x lts branch

- CONTRIBUTING.md
- owlbot.py
Updating CONTRIBUTING.md as per go/java-repos-contrib-guidelines
b/323273913
If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).
> chore: updating CONTRIBUTING.md

- README.md
It took me a while to find the right page
> docs: Update README.md to point to the current documentation page

- pom.xml
- renovate.json
Downgrading guava version to 33.1.0 for consistency.
> deps: downgrading guava version to 33.1.0 for consistency

- .github/workflows/ci.yaml
this is order to support latest graalvm update
> chore: add unit tests again runtime JDK 24
