google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleIdTokenVerifier.java
Both "accounts.google.com" and "https://accounts.google.com" can be generated
by Google. Let either of them validate. Since the verifier is not aware of the
way the id token was retrieved, simply make the issuers a list and consider any
in the list as equivalent.
-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=106320509
=> Support Google's new issuer that includes scheme

google-api-client-appengine/src/main/java/com/google/api/client/googleapis/extensions/appengine/auth/oauth2/AppIdentityCredential.java, google-api-client-appengine/src/main/java/com/google/api/client/googleapis/extensions/appengine/testing/auth/oauth2/MockAppIdentityService.java, google-api-client-appengine/src/test/java/com/google/api/client/googleapis/extensions/appengine/auth/oauth2/AppIdentityCredentialTest.java
This method currently always returns null in App Engine environment, which is a major problem when working with application default credentials. Also the associated `refreshToken()` method always returns false. This fix enables users to call `refreshToken()` and `getAccessToken()` on application default credentials in the App Engine environment. 
I'm not very familiar with this codebase, and hence it may not be complete or even fully accurate. Feedback appreciated.
=> Possible Fix for AppIdentityCredentialWrapper.getAccessToken() Method

google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClient.java
Fixes [#1073](https://github.com/google/google-api-java-client/issues/1073)
[#1087](https://github.com/google/google-api-java-client/pull/1087) aimed to fix this (and might have for some cases) but when I use it `batchPath` is `null` when not set and not an empty string.
=> Handle case when batchPath is null

google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpDownloader.java
This PR tries to fix #937.
This PR breaks `clirr` check with the following error:
> Parameter 2 of 'public com.google.api.client.googleapis.media.MediaHttpDownloader setContentRange(long, int)' has changed its type to long
I don't see any major issue with this as `MediaHttpDownloader.lastBytePos` field is already a `long`, but correct me if I'm wrong.
=> Change lastBytePos to long in MediaHttpDownloader.setContentRange

google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/DefaultCredentialProvider.java
The method runningOnAppEngine was recently renamed to useGAEStandardAPI, and
its logic was changed in https://github.com/google/google-api-java-client/pull/1109 and https://github.com/google/google-api-java-client/commit/75ba03c89a4290fabbb66823f7037ff28ce5f4b9.
This PR reverts back to the original logic before either of those commits.
The reason for the revert is that several deployments failed with this change internally. See b/111173267, b/111149869.
This change has already been submitted internally. This PR simply syncs the internal change to external. See me for more details if you're curious.
=> revert runningOnAppEngine changes

google-api-client-assembly/android-properties/google-http-client-jdo-1.24.0-SNAPSHOT.jar.properties
When the assembly project is {compiled|deployed} (one of those two?), it generates sources. Among those sources are the google-http-java-client-jdo-<version>.jar file in libs-sources. This is fine, but the release process expects a .jar.properties file in libs/. This commit adds it.
Prior to this commit, people were scratching their heads during release and adding it manually.
ejona@ was the one that discovered the solution to this problem.
=> add jdo jar properties to android assembly

pom.xml
Fixes https://github.com/google/google-api-java-client/issues/1084
httpclient 4.5.5
jackson 2.9.6
There are currently three public CVEs for httpclient 4.0.1.
Filename: httpclient-4.0.1.jar | Reference: CVE-2011-1498 | CVSS Score: 4.3 | Category: CWE-200 Information Exposure | Apache HttpClient 4.x before 4.1.1 in Apache HttpComponents, when used with an authenticating proxy server, sends the Proxy-Authorization header to the origin server, which allows remote web servers to obtain sensitive information by logging this header.
Filename: httpclient-4.0.1.jar | Reference: CVE-2014-3577 | CVSS Score: 5.8 | org.apache.http.conn.ssl.AbstractVerifier in Apache HttpComponents HttpClient before 4.3.5 and HttpAsyncClient before 4.0.2 does not properly verify that the server hostname matches a …
=> Library security updates.

google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java, google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java
To get better visibility into which Java versions/environments users are using, we want to add a header to all API requests that identify the client's language version (and other relevant environment versions).
See https://cloud.google.com/apis/docs/system-parameters
=> Add X-Goog-Api-Client header

google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.java, google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/GoogleCredentialTest.java
adds a toBuilder() method which creates a mutable version of the credential
object preloaded with all values from the credential.
adds a createDelegated(String user) method which allows creation of
a credential with correct user delegation from an existing credential
=> adds methods to create delegated credentials and builder

google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.java
In order to overcome problems when running from inside jar.
=> Also accept InputStream at setServiceAccountPrivateKeyFromP12File

.gitignore, google-api-client-appengine/src/main/java/com/google/api/client/googleapis/extensions/appengine/testing/auth/oauth2/MockAppIdentityService.java
Updating the appengine sdk in #1178 introduced a new abstract method that was not implemented.
=> Fix AppEngine tests

google-api-client-appengine/pom.xml
@chingor13 Fixes #1180 
- [X ] Tests pass
- [ X] Appropriate docs were updated (if necessary)
=>  App Engine standard uses Java 7 or Java 8, not 6 and not 9 or later

README.md
=> Add the ending Java 6 support notice to README

google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java, google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java
=> Fix possible NPE when missing os.version system property

google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpUploader.java, google-api-client/src/test/java/com/google/api/client/googleapis/media/MediaHttpUploaderTest.java
Wait until the content chunk is ready first.
Fixes internal bug b/118449379
=> Delay request initialization for resumable upload

google-api-client-android/pom.xml, google-api-client-appengine/pom.xml, google-api-client-gson/pom.xml, google-api-client-jackson2/pom.xml, google-api-client-java6/pom.xml, google-api-client-protobuf/pom.xml, google-api-client-servlet/pom.xml, google-api-client-xml/pom.xml, google-api-client/pom.xml, pom.xml
We're dropping Java 6 in the next release, so set the maven-compiler to use source level 1.7 and to compile to 1.7 binary. Also update animal-sniffer-plugin to java17 to allow 1.7 source.
=> Compile to Java 1.7 binary

.kokoro/continuous/java11.cfg, .kokoro/presubmit/java11.cfg, README.md, google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java, pom.xml
=> Add Java 11 test configs

README.md
Fixes: Capitalized and made the Heading style under main "Google APIs Client Library for Java" similar.
Removed extra "are" in line 166 and extra word, "stay" from content, and removed some such errors and redundancy.
=> edited and removed some redundancy

google-api-client/src/main/java/com/google/api/client/googleapis/testing/auth/oauth2/MockTokenServerTransport.java, pom.xml
`MockTokenServerTransport` will now handle the legacy endpoint and log a warning message to update your credentials (if you are using the legacy endpoint).
Fixes #1151
=> Handle the legacy endpoint in the MockTokenServerTransport

.kokoro/release/drop.sh, .kokoro/release/promote.sh, README.md, google-api-client-android/pom.xml, google-api-client-appengine/pom.xml, google-api-client-assembly/pom.xml, google-api-client-bom/README.md, google-api-client-bom/pom.xml, google-api-client-gson/pom.xml, google-api-client-jackson2/pom.xml, google-api-client-java6/pom.xml, google-api-client-protobuf/pom.xml, google-api-client-servlet/pom.xml, google-api-client-xml/pom.xml, google-api-client/pom.xml, google-api-client/src/main/java/com/google/api/client/googleapis/apache/GoogleApacheHttpTransport.java, pom.xml, versions.txt
01-14-2019 13:18 PST
- Java 6 support was dropped ([#1222](https://github.com/google/google-oauth-java-client/pull/1222))
- Handle the legacy endpoint in the MockTokenServerTransport ([#1232](https://github.com/google/google-api-java-client/pull/1232))
- Set expires_in to an hour instead of 1000 hours ([#1229](https://github.com/google/google-api-java-client/pull/1229))
- Remove ClientLogin ([#1224](https://github.com/google/google-api-java-client/pull/1224))
- Remove usage of deprecated Backoff from google-http-java-client ([#1221](https://github.com/google/google-api-java-client/pull/1221))
- Update guava to 26.0-android ([#1218](https://github.com/google/google-api-java-client/pull/1218))
- Fix old links to code.google.com …
=> Release google-api-java-client v1.28.0

google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpDownloader.java
Fixes https://github.com/googleapis/google-cloud-java/issues/3929
=> 3929: Changed to Guava ByteStreams.copy() that has a bit better performance

google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpDownloader.java, google-api-client/src/test/java/com/google/api/client/googleapis/media/MediaHttpDownloaderTest.java
=> 956: Chech for null to prevent autoboxing NPE.

google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpDownloader.java, google-api-client/src/test/java/com/google/api/client/googleapis/media/MediaHttpDownloaderTest.java
=> Infinite cycle with MediaHttpDownloader setContentRange download

google-api-client-android/src/main/java/com/google/api/client/googleapis/extensions/android/gms/auth/GoogleAccountCredential.java
=> Fix Replaced invalidateToken method to clearToken

google-api-client-gson/pom.xml, google-api-client-jackson2/pom.xml
This fixes OSGI metadata for the jackson2 package. Others still need to be done. 
- [X ] Tests pass
- [ X] Appropriate docs were updated (if necessary)
=> merge OSGI metadata

google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/CloudShellCredential.java, google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.java
The fancy automatic credentials for Application Default Credentials and CloudShell should be handled by [google-auth-library](https://github.com/googleapis/google-auth-library-java). That library provides [an adapter](https://github.com/googleapis/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/http/HttpCredentialsAdapter.java) that can be used with google-http-client.
Note that this still provides the oauth2 helpers for handling 3-legged OAuth2.
=> Deprecate the GoogleCredential and CloudShellCredential classes

google-api-client-appengine/pom.xml, google-api-client-gson/pom.xml, google-api-client-jackson2/pom.xml, google-api-client-java6/pom.xml, google-api-client-protobuf/pom.xml, google-api-client-servlet/pom.xml, google-api-client-xml/pom.xml, google-api-client/pom.xml, pom.xml, versions.txt
* Bump oauth and http client dependencies.
* Stop version bumping for oauth and http clients at release time
=> Update http/oauth dependencies to 1.29

README.md, google-api-client-android/pom.xml, google-api-client-appengine/pom.xml, google-api-client-assembly/pom.xml, google-api-client-bom/README.md, google-api-client-bom/pom.xml, google-api-client-gson/pom.xml, google-api-client-jackson2/pom.xml, google-api-client-java6/pom.xml, google-api-client-protobuf/pom.xml, google-api-client-servlet/pom.xml, google-api-client-xml/pom.xml, google-api-client/pom.xml, pom.xml, versions.txt
05-20-2019 10:18 PDT
- Deprecate the GoogleCredential and CloudShellCredential classes ([#1258](https://github.com/google/google-api-java-client/pull/1258))
- More OSGI metadata ([#1253](https://github.com/google/google-api-java-client/pull/1253))
- Fix OSGI metadata for gson and jackson2 packages ([#1251](https://github.com/google/google-api-java-client/pull/1251))
- Fix Replaced invalidateToken method to clearToken ([#1243](https://github.com/google/google-api-java-client/pull/1243))
- Infinite cycle with MediaHttpDownloader setContentRange download ([#1242](https://github.com/google/google-api-java-client/pull/1242))
- Check for null to prevent autoboxing NPE. ([#1241](https://github.com/google/google-api-java-client/pull/1241))
- …
=> Release google-api-java-client v1.29.0

README.md, google-api-client-android/pom.xml, google-api-client-appengine/pom.xml, google-api-client-assembly/pom.xml, google-api-client-bom/README.md, google-api-client-bom/pom.xml, google-api-client-gson/pom.xml, google-api-client-jackson2/pom.xml, google-api-client-java6/pom.xml, google-api-client-protobuf/pom.xml, google-api-client-servlet/pom.xml, google-api-client-xml/pom.xml, google-api-client/pom.xml, pom.xml, versions.txt
06-03-2019 22:34 PDT
- Update dependency com.google.oauth-client:google-oauth-client to v1.29.2 ([#1290](https://github.com/google/google-api-java-client/pull/1290))
- Update dependency com.google.http-client:google-http-client to v1.29.2 ([#1288](https://github.com/google/google-api-java-client/pull/1288))
=> Release google-api-java-client v1.29.2

google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java, google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java
Add option to return raw input stream for response
=> Add option to return raw input stream for response

README.md, google-api-client-android/pom.xml, google-api-client-appengine/pom.xml, google-api-client-assembly/pom.xml, google-api-client-bom/README.md, google-api-client-bom/pom.xml, google-api-client-gson/pom.xml, google-api-client-jackson2/pom.xml, google-api-client-java6/pom.xml, google-api-client-protobuf/pom.xml, google-api-client-servlet/pom.xml, google-api-client-xml/pom.xml, google-api-client/pom.xml, google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java, google-api-client/src/main/java/com/google/api/client/googleapis/services/CommonGoogleClientRequestInitializer.java, google-api-client/src/main/java/com/google/api/client/googleapis/services/json/CommonGoogleJsonClientRequestInitializer.java, pom.xml, versions.txt
06-18-2019 08:59 PDT
- Extensible client options ([#1263](https://github.com/google/google-api-java-client/pull/1263))
- Add option to return raw input stream for response ([#1323](https://github.com/google/google-api-java-client/pull/1323))
- Update dependency org.apache.httpcomponents:httpclient to v4.5.9 ([#1316](https://github.com/google/google-api-java-client/pull/1316))
- Group AppEngine deps for renovate
- Import google-http-client-bom and google-oauth-client-bom. ([#1309](https://github.com/google/google-api-java-client/pull/1309))
- Update dependency com.google.http-client:google-http-client to v1.30.0 ([#1307](https://github.com/google/google-api-java-client/pull/1307))
- Update dependency …
=> Release google-api-java-client v1.30.0

.kokoro/release/stage.sh, README.md, google-api-client-android/pom.xml, google-api-client-appengine/pom.xml, google-api-client-assembly/pom.xml, google-api-client-bom/README.md, google-api-client-bom/pom.xml, google-api-client-gson/pom.xml, google-api-client-jackson2/pom.xml, google-api-client-java6/pom.xml, google-api-client-protobuf/pom.xml, google-api-client-servlet/pom.xml, google-api-client-xml/pom.xml, google-api-client/pom.xml, pom.xml, versions.txt
06-19-2019 16:53 PDT
- Close InputStream on error during resumable upload ([#1324](https://github.com/google/google-api-java-client/pull/1324))
- Update dependency com.google.oauth-client:google-oauth-client-bom to v1.30.1 ([#1314](https://github.com/google/google-api-java-client/pull/1314))
- Update dependency com.google.http-client:google-http-client-bom to v1.30.1 ([#1311](https://github.com/google/google-api-java-client/pull/1311))
- Bump next snapshot ([#1328](https://github.com/google/google-api-java-client/pull/1328))
=> Release google-api-java-client v1.30.1

google-api-client/src/main/java/com/google/api/client/googleapis/batch/BatchRequest.java, google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClient.java
Users should obtain a `BatchRequest` instance via their client's `batch(HttpRequestInitializer)` method.
* Deprecates the public BatchRequest constructor
* Logs a WARNING message if you try to make a request against the global batch endpoint.
=> Deprecate BatchRequest constructor

README.md, google-api-client-android/pom.xml, google-api-client-appengine/pom.xml, google-api-client-assembly/pom.xml, google-api-client-bom/README.md, google-api-client-bom/pom.xml, google-api-client-gson/pom.xml, google-api-client-jackson2/pom.xml, google-api-client-java6/pom.xml, google-api-client-protobuf/pom.xml, google-api-client-servlet/pom.xml, google-api-client-xml/pom.xml, google-api-client/pom.xml, pom.xml, versions.txt
07-01-2019 13:05 PDT
- Migrate batching, media upload/download docs from developers.google.com ([#1334](https://github.com/google/google-api-java-client/pull/1334))
=> Release google-api-java-client v1.30.2

README.md, google-api-client-android/pom.xml, google-api-client-appengine/pom.xml, google-api-client-assembly/pom.xml, google-api-client-gson/pom.xml, google-api-client-jackson2/pom.xml, google-api-client-java6/pom.xml, google-api-client-protobuf/pom.xml, google-api-client-servlet/pom.xml, google-api-client-xml/pom.xml, google-api-client/pom.xml, google-api-client/src/main/java/com/google/api/client/googleapis/GoogleUtils.java, pom.xml, versions.txt
=> Release google-api-java-client v1.26.1

README.md, google-api-client-android/pom.xml, google-api-client-appengine/pom.xml, google-api-client-assembly/pom.xml, google-api-client-bom/README.md, google-api-client-bom/pom.xml, google-api-client-gson/pom.xml, google-api-client-jackson2/pom.xml, google-api-client-java6/pom.xml, google-api-client-protobuf/pom.xml, google-api-client-servlet/pom.xml, google-api-client-xml/pom.xml, google-api-client/pom.xml, google-api-client/src/main/java/com/google/api/client/googleapis/GoogleUtils.java, pom.xml, versions.txt
=> Release google-api-java-client v1.27.1

README.md, google-api-client-android/pom.xml, google-api-client-appengine/pom.xml, google-api-client-assembly/pom.xml, google-api-client-bom/README.md, google-api-client-bom/pom.xml, google-api-client-gson/pom.xml, google-api-client-jackson2/pom.xml, google-api-client-java6/pom.xml, google-api-client-protobuf/pom.xml, google-api-client-servlet/pom.xml, google-api-client-xml/pom.xml, google-api-client/pom.xml, google-api-client/src/main/java/com/google/api/client/googleapis/GoogleUtils.java, pom.xml, versions.txt
=> Release google-api-java-client v1.28.1

README.md, google-api-client-android/pom.xml, google-api-client-appengine/pom.xml, google-api-client-assembly/pom.xml, google-api-client-bom/README.md, google-api-client-bom/pom.xml, google-api-client-gson/pom.xml, google-api-client-jackson2/pom.xml, google-api-client-java6/pom.xml, google-api-client-protobuf/pom.xml, google-api-client-servlet/pom.xml, google-api-client-xml/pom.xml, google-api-client/pom.xml, google-api-client/src/main/java/com/google/api/client/googleapis/GoogleUtils.java, pom.xml, versions.txt
=> Release google-api-java-client v1.29.3

google-api-client/src/main/java/com/google/api/client/googleapis/GoogleUtils.java, google-api-client/src/test/java/com/google/api/client/googleapis/GoogleUtilsTest.java
Add markers for version replacement so this constant is kept up to date via releasetool.
See https://github.com/googleapis/releasetool/pull/216
=> Fix VERSION constant

google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java, google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java
=> Update x-goog-api-client header to use gl-java and gdcl tokens

README.md, google-api-client-android/pom.xml, google-api-client-appengine/pom.xml, google-api-client-assembly/pom.xml, google-api-client-bom/README.md, google-api-client-bom/pom.xml, google-api-client-gson/pom.xml, google-api-client-jackson2/pom.xml, google-api-client-java6/pom.xml, google-api-client-protobuf/pom.xml, google-api-client-servlet/pom.xml, google-api-client-xml/pom.xml, google-api-client/pom.xml, google-api-client/src/main/java/com/google/api/client/googleapis/GoogleUtils.java, pom.xml, versions.txt
09-12-2019 15:56 PDT
- Update x-goog-api-client header to use gl-java and gdcl tokens ([#1354](https://github.com/google/google-api-java-client/pull/1354))
- Fix VERSION constant ([#1355](https://github.com/google/google-api-java-client/pull/1355))
- deps: update dependency com.google.oauth-client:google-oauth-client-bom to v1.30.2 ([#1376](https://github.com/google/google-api-java-client/pull/1376))
- deps: update project.http.version to v1.32.0 ([#1374](https://github.com/google/google-api-java-client/pull/1374))
- deps: update App Engine SDK to 1.9.65, animal-sniffer to 1.16 ([#1364](https://github.com/google/google-api-java-client/pull/1364))
- deps: update protobuf to 3.9.1 ([#1365](https://github.com/google/google-api-java-client/pul …
=> Release google-api-java-client v1.30.3

google-api-client/src/main/java/com/google/api/client/googleapis/testing/json/GoogleJsonResponseExceptionFactoryTesting.java
Currently, `GoogleJsonResponseException`s created with `GoogleJsonResponseExceptionFactoryTesting` will have null `#getDetails()`.
=> Add details to GoogleJsonResponseExceptions created with GoogleJsonResponseExceptionFactoryTesting

google-api-client/pom.xml, google-api-client/src/main/java/com/google/api/client/googleapis/GoogleUtils.java, google-api-client/src/main/properties/com/google/api/client/googleapis/google-api-client.properties, google-api-client/src/test/java/com/google/api/client/googleapis/GoogleUtilsTest.java, pom.xml
This PR allows the GoogleUtils to inspect its own version at start time. If it's running from a package, it can fetch the version from the package manifest's implementation version. If it's not, it can read it from a properties file created at compile time to read the version.
Note:
* This is similar to how gax inspects its own version for the x-goog-api-client header.
* We needed to update the checkstyle plugin to make this pass
=> fix: grab version from package metadata

README.md
=> chore: fix link to documentation guide

pom.xml
=> remove jackson2 variable we don't use

google-api-client/src/main/java/com/google/api/client/googleapis/GoogleUtils.java
=> fix: update GoogleUtils#getVersion() to use stable logic

google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java
In a a future commit the wrapping of these InputStreams will change.
This should ensure the tests will still pass while at the same time
validating the raw InputStream behavior still works.
=> fix: future test breakage

google-api-client/src/test/java/com/google/api/client/googleapis/batch/BatchRequestTest.java, pom.xml
@chingor13 @suztomo This one require test changes and was too complex for renovabot to handle
=> deps: update http client

README.md, google-api-client/pom.xml, google-api-client/src/main/java/com/google/api/client/googleapis/GoogleUtils.java, google-api-client/src/main/resources/META-INF/proguard/google-api-client.pro
R8 provides a mechanism for embedding proguard files, which obviates the need for a compile-time dependency on an Android library in core.
Not well documented but reasonably commonly used.
https://twitter.com/jakewharton/status/1004401938467876865?lang=en
https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro
Unfortunately, without a regression test I'm not 100% sure this works, nor am I an Android developer with much confidence, just following the pattern of other libraries :)
Fixes #1487
=> fix: use embedded Proguard configuration instead of compile-time annotation

synth.metadata
Fixes #1514
Somehow, the synth.metadata picked up the autosynth git remote which is invalid.
=> chore: fix synth.metadata

docs/android.md, docs/errors.md
=> docs: removes reference to deprecated service (Google+)

google-api-client/pom.xml, google-api-client/src/main/java/com/google/api/client/googleapis/apache/GoogleApacheHttpTransport.java, google-api-client/src/main/java/com/google/api/client/googleapis/apache/package-info.java, google-api-client/src/main/java/com/google/api/client/googleapis/apache/v2/GoogleApacheHttpTransport.java, google-api-client/src/main/java/com/google/api/client/googleapis/apache/v2/package-info.java
* Introduces a separate GoogleApacheHttpTransport that return the v2 ApacheHttpTransport implementation.
* Deprecates the original GoogleApacheHttpTransport in favor of this one.
=> feat: add GoogleApacheHttpTransport that uses the v2 ApacheHttpTransport implementation

google-api-client/src/main/java/com/google/api/client/googleapis/apache/v2/GoogleApacheHttpTransport.java, google-api-client/src/test/java/com/google/api/client/googleapis/apache/v2/GoogleApacheHttpTransportTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/mtls/MtlsTransportBaseTest.java
For `GoogleApacheHttpTransport`, `socketFactory` has to be registered for https, and provided to `connectionManager`. This PR does the following:
- register socket factory for `http` and `https`, and pass to connection manager ([reference](https://github.com/mydevotion/httpclient/blob/master/httpclient/src/main/java/org/apache/http/impl/conn/PoolingHttpClientConnectionManager.java#L109))
- removed `.setSSLSocketFactory(socketFactory)` from the chain of calls after `HttpClientBuilder.create()`, since it will be overwritten by `.setConnectionManager(connectionManager)`
=> fix: socketfactory not registered for apache

docs/oauth-2.0.md
=> docs: Update the documentation link for GoogleCredential from deprecated version to newer version

google-api-client-appengine/src/test/java/com/google/api/client/googleapis/extensions/appengine/auth/oauth2/AppIdentityCredentialTest.java, google-api-client-jackson2/src/main/java/com/google/api/client/googleapis/notifications/json/jackson2/JacksonNotificationCallback.java, google-api-client/pom.xml, google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleAuthorizationCodeTokenRequest.java, google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleRefreshTokenRequest.java, google-api-client/src/main/java/com/google/api/client/googleapis/json/package-info.java, google-api-client/src/main/java/com/google/api/client/googleapis/notifications/TypedNotificationCallback.java, google-api-client/src/main/java/com/google/api/client/googleapis/notifications/json/JsonNotificationCallback.java, google-api-client/src/main/java/com/google/api/client/googleapis/testing/auth/oauth2/MockGoogleCredential.java, google-api-client/src/main/java/com/google/api/client/googleapis/testing/auth/oauth2/MockTokenServerTransport.java, google-api-client/src/main/java/com/google/api/client/googleapis/testing/compute/MockMetadataServerTransport.java, google-api-client/src/main/java/com/google/api/client/googleapis/util/Utils.java, google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/DefaultCredentialProviderTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/GoogleAuthorizationCodeFlowTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/GoogleAuthorizationCodeTokenRequestTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/GoogleCredentialTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/GoogleIdTokenVerifierTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/auth/oauth2/GooglePublicKeysManagerTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/batch/BatchRequestTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/compute/ComputeCredentialTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/json/GoogleJsonErrorContainerTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/json/GoogleJsonErrorTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/services/json/AbstractGoogleJsonClientTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/services/json/CommonGoogleJsonClientRequestInitializerTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/testing/json/GoogleJsonResponseExceptionFactoryTestingTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/util/UtilsTest.java
=> fix: use Gson instead of Jackson

.github/workflows/ci.yaml, checkstyle-suppressions.xml, checkstyle.xml, pom.xml
=> ci: installing google-play-services artifact for Windows

.github/sync-repo-settings.yaml
This adds other GitHub Actions in the repository
=> ci: required check to remove Kokoro Linkage Monitor

.github/workflows/ci.yaml
For https://github.com/googleapis/google-api-java-client/pull/1717 ("ci / linkage-monitor" is failing), this change by synthtool expects the ci.yaml
to use the Linkage Monitor GitHub Actions and it deletes .kokoro/linkage-monitor.sh.
However this repository excludes ci.yaml from being managed by synthtool. Therefore we need to manually maintain ci.yaml to stop using linkage-monitor.sh.
---
=> ci: linkage monitor CI update to stop using .kokoro/linkage-monitor.sh

.github/sync-repo-settings.yaml
- Kokoro unit tests for Java 7 - Java 11 are now performed by GitHub Actions:units (7) - units (11)
- CLIRR takes over "Kokoro: Test: Binary Compatibility".
Created corresponding cl/360270976 to stop these Kokoro jobs. Note that this PR needs to come first and and reflect the change to the repository settings, before I submit the CL.
@chingor13 @stephaniewang526
=> ci: removing Kokoro from required checks

pom.xml
@Neenu1995 @suztomo fixes #1784
=> fix: remove deprecated parent pom

google-api-client/src/main/java/com/google/api/client/googleapis/json/GoogleJsonError.java, google-api-client/src/test/java/com/google/api/client/googleapis/json/GoogleJsonErrorTest.java, google-api-client/src/test/java/com/google/api/client/googleapis/json/GoogleJsonResponseExceptionTest.java, google-api-client/src/test/resources/com/google/api/client/googleapis/json/error.json
Fixes b/185405327
Invalid parameter error message does not contain details about which parameter is the invalid one. These fields have been added to GoogleJsonError object.
=> fix: update GoogleJsonError object to accomodate all fields in Invalid parameter exception

pom.xml
Updates cloud rad doc generation to use new [doclet](https://github.com/googleapis/java-docfx-doclet). Added the new doclet jar to cloud-devrel-kokoro-resources/docfx bucket
=> chore: update cloud-rad doclet

google-api-client-appengine/pom.xml
@chingor13 I think there are still some old projects using Java 7 on app engine, but Java 6 should be gone.
=> fix: bring comment up to date with code

.github/workflows/ci.yaml
Removing linkage-monitor check from GitHub Check. It's not a required check.
=> ci: uninstalling linkage-monitor

google-api-client-java6/src/main/java/com/google/api/client/googleapis/extensions/java6/auth/oauth2/GooglePromptReceiver.java
OAuth [out-of-band](https://developers.google.com/identity/protocols/oauth2/native-app#manual-copypaste) (OOB) is a legacy flow developed to support native clients which do not have a redirect URI like web apps to accept the credentials after a user approves an OAuth consent request. The OOB flow poses a remote phishing risk and clients must migrate to an alternative method to protect against this vulnerability. New clients will be unable to use this flow starting on Feb 28, 2022.
[More details.](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html)
=> feat: deprecate OOB auth flow in GooglePromptReceiver

pom.xml
Reverting update dependency com.google.protobuf:protobuf-java to v3.20.0 (#2029)
This reverts commit b36c162de0a1df8a0a5e4058037dca3db2470883.
This version aligns other dependencies for Cloud client libraries, just in case we need to release this repository soon.
=> deps: revert protobuf to 3.19

.github/release-please.yml, .github/sync-repo-settings.yaml
enable releases
go/backport-releases:
```
$ release-brancher create-pull-request \
--branch-name="1.34.x" \
--target-tag="v1.34.0" \
--repo="googleapis/google-api-java-client" \
--pull-request-title="feat: next release from main branch is 1.35.0" \
--release-type=java-backport --github-token ${GITHUB_TOKEN}
```
=> feat: next release from main branch is 1.35.0

pom.xml
deps: upgrade google-http-client 1.41.8 (which uses appengine-api 1.9.X)
deps: downgrade appengine-api to 1.9.X
=> deps: google-http-client to a version that depends on appengine-api to 1.9.X

pom.xml
This PR manually declares the `commons-codec` version to `1.15`. 
It was discovered that `commons-codec-1.11.jar` has a    a medium vulnerability (https://sca.analysiscenter.veracode.com/vulnerability-database/security/sca/vulnerability/sid-22742/summary). This vulnerability does not have a CVE and it is related to Insecure Input Validation and encoding. 
This is an indirect dpendency that the API client library uses indirectly by using Apache HttpClient.
Any version of codec v1.13+ should have the fix for this vulnerability.
=> fix: update and declare commons-codec dependency

google-api-client/pom.xml, pom.xml
Turns out https://github.com/googleapis/google-api-java-client/pull/2195 only fixed half the issue. `commons-codec` needs to be declared as a dependency within the `google-api-client`'s `pom.xml` as well.
=> fix: pinning commons-codec dependency in google-api-client

google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java, google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientTest.java
Fixes #2222 
- Upload to have applicationName as User-Agent
- request initializer to set user-agent header
How I confirmed the fix:
I locally installed this branch via `mvn install` and specified the SNAPSHOT version of the BOM:
```xml
<dependencyManagement>
<dependencies>
<dependency>
<groupId>com.google.api-client</groupId>
<artifactId>google-api-client-bom</artifactId>
<version>2.1.3-SNAPSHOT</version>
<type>pom</type>
<scope>import</scope>
</dependency>
</dependencies>
</dependencyManagement>
<dependencies>
<dependency>
<groupId>com.google.apis</groupId>
<artifactId>google-api-services-storage</artifactId>
<version>v1-rev20220705-2.0.0</version>
</dependency>
...
```
I ran @BenWhitehead 's reproducer (with my small modification):
```java
package org.example;
import static …
```
=> fix: media upload to have applicationName as User-Agent

renovate.json
Following https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/java_library/renovate.json#L15
=> build: RenovateBot shouldn't touch requirements.txt

google-api-client-java6/src/main/java/com/google/api/client/googleapis/extensions/java6/auth/oauth2/GooglePromptReceiver.java, google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleOAuthConstants.java
Followup of https://github.com/googleapis/google-api-java-client/pull/2242/files#r1087160426
=> docs: adding deprecated annotation for OOB flow and guide for migration

clirr-ignored-differences.xml
Fixes #2267. This is to unblock failing clirr checks in PRs since v2.2.0, as follow-up to https://github.com/googleapis/google-api-java-client/pull/2242#discussion_r1086200169.
Note: this PR and the ci/windows fix in https://github.com/googleapis/google-api-java-client/pull/2269 mutually unblock each other (and a number of other open PRs in this repo).
=> chore: add clirr ignore for deprecated OOB flow

google-api-client-appengine/src/main/java/com/google/api/client/googleapis/extensions/appengine/auth/oauth2/AppIdentityCredential.java, google-api-client-gson/src/main/java/com/google/api/client/googleapis/notifications/json/gson/GsonNotificationCallback.java, google-api-client-jackson2/src/main/java/com/google/api/client/googleapis/notifications/json/jackson2/JacksonNotificationCallback.java, google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/CloudShellCredential.java, google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/DefaultCredentialProvider.java, google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleIdToken.java, google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/package-info.java, google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpUploader.java, google-api-client/src/main/java/com/google/api/client/googleapis/notifications/StoredChannel.java, google-api-client/src/main/java/com/google/api/client/googleapis/notifications/json/JsonNotificationCallback.java
These typos were caught by internal presubmits during the latest import process.
=> chore: fix typos

google-api-client/src/main/java/com/google/api/client/googleapis/GoogleUtils.java
…operties
- Make it file shading friendly like https://github.com/googleapis/google-http-java-client/pull/1046
- Avoid set proguard config to read this file. b/279795343#comment2
=> Read absolute path of google-api-client.properties

.github/workflows/ci.yaml
This reverts commit 8f1b4c9aeb641cf2a1e8d43c1e8b8adcbbf9b86d (added in #2269).
Resolves #2273.
=> ci: revert maven wrapper workaround for CI/Windows check

docs/setup.md
I'm checking how the document https://googleapis.github.io/google-api-java-client/setup.html is updated by this libraries-bom version upgrade.
=> docs: latest libraries-bom

google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequest.java, google-api-client/src/main/java/com/google/api/client/googleapis/testing/services/MockGoogleClientRequest.java, google-api-client/src/test/java/com/google/api/client/googleapis/services/AbstractGoogleClientRequestTest.java
Changes:
- Pass `X-Google-Api-Version` as a header as part of requests if apiVersion exists in the Discovery Doc
Corresponding generator change https://github.com/googleapis/google-api-java-client-services/pull/20930
This PR will go in first then merge in the generator change once this is released and in maven central.
Logs:
```
2024-05-09 14:37:57,833 CONFIG   com.google.api.client.http.HttpTransport - -------------- REQUEST  --------------
GET {URL}
Accept-Encoding: gzip
Authorization: Bearer {BEARER_TOKEN}
User-Agent: DeltaV Example Java App Google-API-Java-Client/2.4.1-SNAPSHOT Google-HTTP-Java-Client/1.44.1 (gzip)
x-goog-user-project: {PROJECT_ID}
x-goog-api-client: gl-java/17.0.10 gdcl/2.4.1 linux/6.6.15
x-google-api-version: v1_20230601
```
=> feat: Add ApiVersion Support

google-api-client-servlet/pom.xml, google-api-client-servlet/src/main/java/com/google/api/client/googleapis/extensions/servlet/notifications/jakarta/NotificationServlet.java, google-api-client-servlet/src/main/java/com/google/api/client/googleapis/extensions/servlet/notifications/jakarta/WebhookUtils.java, google-api-client-servlet/src/main/java/com/google/api/client/googleapis/extensions/servlet/notifications/jakarta/package-info.java, pom.xml
Fixes #2260
Internal bug b/342581012.
I copied the WebhookUtils and WebhookUtils (https://github.com/googleapis/google-api-java-client/tree/2d25655b94dc1ae93b5c3a97046daf6a35a9923b/google-api-client-servlet/src/main/java/com/google/api/client/googleapis/extensions/servlet/notifications ) replacing the javax namespace with the jakarta.servlet namespace.
This is the same methology as https://github.com/googleapis/google-oauth-java-client/pull/1115.
- Replaced javax with jakarta and declared the dependency with
provided scope.
- Keeping the classes as `Beta` annotated.
- WebhookHeaders in the original package does not reference the javax namespace.
- No tests exist for the classes.
- Added `@since 2.6.0` as the last release was 2.5.1.
=> feat: WebHookUtil classes using the jakarta namespace

renovate.json
Pinning jakarta servlet API v5 because v6 does not work with Java 8 compilation. RenovateBot would create unnecessary pull requests such as https://github.com/googleapis/google-api-java-client/pull/2486#issuecomment-2129988178.
Using matchPackageNames https://docs.renovatebot.com/configuration-options/#matchpackagenames. No regular expression is needed.
=> chore: pinning jakarta servlet API v5

google-api-client/src/main/java/com/google/api/client/googleapis/json/GoogleJsonError.java, google-api-client/src/main/java/com/google/api/client/googleapis/json/GoogleJsonResponseException.java
Fixes #2513 
https://developers.google.com/api-client-library/java/google-api-java-client/errors points to https://cloud.google.com/apis/design/errors for defining the error response format.
=> docs: fix error response format url

google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.java
=> fix: Add warnings to users about using credentials from external sources

.github/release-please.yml, .github/sync-repo-settings.yaml
=> feat: next release from main branch is 2.8.0

google-api-client-bom/pom.xml, pom.xml
The nexus-staging-maven-plugin extension is wrapped by a profile "release-sonatype" because the extension interferes with maven-deploy-plugin. Example error: `[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.7.0:deploy (injected-nexus-deploy) on project google-api-client-bom: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.7.0:deploy failed: Server credentials with ID "sonatype-nexus-staging" not found! -> [Help 1]`
We use maven-deploy-plugin to upload artifacts to Artifact Registry, as well as to locally create bundle for Central Portal API.
This follows https://github.com/googleapis/google-oauth-java-client/commit/8e6ce3aeea86c3019677d599f0e0d82ffdadbd04.
=> ci: wrap nexus-staging-maven-plugin in a profile

.github/workflows/ci.yaml
If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).
=> ci: upgrade tests to JDK 25
